name = "itheme-404"
license = "GPL-3.0"
licenselink = "https://github.com/floyd-li/hugo-theme-itheme/blob/master/LICENSE"
description = "An Apple's Style Theme"
homepage = "https://github.com/floyd-li/hugo-theme-itheme"
demosite = "https://hugo-theme-itheme.netlify.app"
tags = ["apple","blog", "newsroom", "light", "dark"]
features = ["blog", "apple", "newsroom"]
[author]
  name = "Liangdi"
  homepage = "https://github.com/liangdi"
[original]
  name = "floyd-li"
  homepage = "https://hugo-theme-itheme.netlify.app"
  repo = "https://github.com/floyd-li/hugo-theme-itheme"
[module]
  [module.hugoVersion]
    min = "0.93.0"
